[package]
name = "pixfix"
version = "0.1.2"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["rt-multi-thread", "macros"] }
image = "0.25.6"
spade = "2.14.0"

[build-dependencies]
winres = "0.1.12"

[profile.release]
strip = true
panic = "abort"